import { Inter, Nunito_Sans } from "next/font/google";
import "./globals.css";
import Herosection from "@/components/Herosection";
import Navbar from "@/components/Navbar";
import About from "@/components/About";
import FeaturedProjects from "@/components/FeaturedProjects";
import Portfolio from "@/components/Portfolio";
import Highlight from "@/components/Highlight";
import Wierdsection from "@/components/Wierdsection";
import LatestInsight from "@/components/LatestInsight";
import Schedulesection from "@/components/Schedulesection";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-nunito-sans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={nunitoSans.className}>
        <Navbar/>
        <Herosection/>
        <About/>
        <FeaturedProjects/>
        <Portfolio/>
        <Highlight/>
        <Wierdsection/>
        <LatestInsight/>
        <Schedulesection/>
        <Footer/>
        {children}
      </body>
    </html>
  );
}


